/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinarTokenRouteImport } from './routes/assinar.$token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedNfsRouteImport } from './routes/_authenticated/nfs'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedTransacoesIndexRouteImport } from './routes/_authenticated/transacoes.index'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated/contratos.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicAbacateWebhookRouteImport } from './routes/api/public/abacate-webhook'
import { Route as AuthenticatedTransacoesNovoRouteImport } from './routes/_authenticated/transacoes.novo'
import { Route as AuthenticatedTransacoesContractIdRouteImport } from './routes/_authenticated/transacoes.$contractId'
import { Route as AuthenticatedContratosNovoRouteImport } from './routes/_authenticated/contratos.novo'
import { Route as AuthenticatedContratosContractIdRouteImport } from './routes/_authenticated/contratos.$contractId'
import { Route as AuthenticatedChatContractIdRouteImport } from './routes/_authenticated/chat.$contractId'
import { Route as AuthenticatedAdminContratosFalhaRouteImport } from './routes/_authenticated/_admin/contratos-falha'
import { Route as AuthenticatedAdminAssinaturasRouteImport } from './routes/_authenticated/_admin/assinaturas'
import { Route as ApiPublicSignTokenRouteImport } from './routes/api/public/sign.$token'
import { Route as ApiPublicAutentiqueWebhookSplatRouteImport } from './routes/api/public/autentique-webhook.$'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarTokenRoute = AssinarTokenRouteImport.update({
  id: '/assinar/$token',
  path: '/assinar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNfsRoute = AuthenticatedNfsRouteImport.update({
  id: '/nfs',
  path: '/nfs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransacoesIndexRoute =
  AuthenticatedTransacoesIndexRouteImport.update({
    id: '/transacoes/',
    path: '/transacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/contratos/',
    path: '/contratos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAbacateWebhookRoute = ApiPublicAbacateWebhookRouteImport.update({
  id: '/api/public/abacate-webhook',
  path: '/api/public/abacate-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransacoesNovoRoute =
  AuthenticatedTransacoesNovoRouteImport.update({
    id: '/transacoes/novo',
    path: '/transacoes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransacoesContractIdRoute =
  AuthenticatedTransacoesContractIdRouteImport.update({
    id: '/transacoes/$contractId',
    path: '/transacoes/$contractId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosNovoRoute =
  AuthenticatedContratosNovoRouteImport.update({
    id: '/contratos/novo',
    path: '/contratos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosContractIdRoute =
  AuthenticatedContratosContractIdRouteImport.update({
    id: '/contratos/$contractId',
    path: '/contratos/$contractId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatContractIdRoute =
  AuthenticatedChatContractIdRouteImport.update({
    id: '/chat/$contractId',
    path: '/chat/$contractId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContratosFalhaRoute =
  AuthenticatedAdminContratosFalhaRouteImport.update({
    id: '/contratos-falha',
    path: '/contratos-falha',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAssinaturasRoute =
  AuthenticatedAdminAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicSignTokenRoute = ApiPublicSignTokenRouteImport.update({
  id: '/api/public/sign/$token',
  path: '/api/public/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutentiqueWebhookSplatRoute =
  ApiPublicAutentiqueWebhookSplatRouteImport.update({
    id: '/api/public/autentique-webhook/$',
    path: '/api/public/autentique-webhook/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/transactions': typeof TransactionsRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/nfs': typeof AuthenticatedNfsRoute
  '/api/chat': typeof ApiChatRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/contratos-falha': typeof AuthenticatedAdminContratosFalhaRoute
  '/chat/$contractId': typeof AuthenticatedChatContractIdRoute
  '/contratos/$contractId': typeof AuthenticatedContratosContractIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/transacoes/$contractId': typeof AuthenticatedTransacoesContractIdRoute
  '/transacoes/novo': typeof AuthenticatedTransacoesNovoRoute
  '/api/public/abacate-webhook': typeof ApiPublicAbacateWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/transacoes/': typeof AuthenticatedTransacoesIndexRoute
  '/api/public/autentique-webhook/$': typeof ApiPublicAutentiqueWebhookSplatRoute
  '/api/public/sign/$token': typeof ApiPublicSignTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/transactions': typeof TransactionsRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/nfs': typeof AuthenticatedNfsRoute
  '/api/chat': typeof ApiChatRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/contratos-falha': typeof AuthenticatedAdminContratosFalhaRoute
  '/chat/$contractId': typeof AuthenticatedChatContractIdRoute
  '/contratos/$contractId': typeof AuthenticatedContratosContractIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/transacoes/$contractId': typeof AuthenticatedTransacoesContractIdRoute
  '/transacoes/novo': typeof AuthenticatedTransacoesNovoRoute
  '/api/public/abacate-webhook': typeof ApiPublicAbacateWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/transacoes': typeof AuthenticatedTransacoesIndexRoute
  '/api/public/autentique-webhook/$': typeof ApiPublicAutentiqueWebhookSplatRoute
  '/api/public/sign/$token': typeof ApiPublicSignTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/transactions': typeof TransactionsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/nfs': typeof AuthenticatedNfsRoute
  '/api/chat': typeof ApiChatRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/_authenticated/_admin/assinaturas': typeof AuthenticatedAdminAssinaturasRoute
  '/_authenticated/_admin/contratos-falha': typeof AuthenticatedAdminContratosFalhaRoute
  '/_authenticated/chat/$contractId': typeof AuthenticatedChatContractIdRoute
  '/_authenticated/contratos/$contractId': typeof AuthenticatedContratosContractIdRoute
  '/_authenticated/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/_authenticated/transacoes/$contractId': typeof AuthenticatedTransacoesContractIdRoute
  '/_authenticated/transacoes/novo': typeof AuthenticatedTransacoesNovoRoute
  '/api/public/abacate-webhook': typeof ApiPublicAbacateWebhookRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/_authenticated/transacoes/': typeof AuthenticatedTransacoesIndexRoute
  '/api/public/autentique-webhook/$': typeof ApiPublicAutentiqueWebhookSplatRoute
  '/api/public/sign/$token': typeof ApiPublicSignTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/transactions'
    | '/assinatura'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/nfs'
    | '/api/chat'
    | '/assinar/$token'
    | '/assinaturas'
    | '/contratos-falha'
    | '/chat/$contractId'
    | '/contratos/$contractId'
    | '/contratos/novo'
    | '/transacoes/$contractId'
    | '/transacoes/novo'
    | '/api/public/abacate-webhook'
    | '/api/public/health'
    | '/api/public/sitemap.xml'
    | '/chat/'
    | '/contratos/'
    | '/transacoes/'
    | '/api/public/autentique-webhook/$'
    | '/api/public/sign/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/transactions'
    | '/assinatura'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/nfs'
    | '/api/chat'
    | '/assinar/$token'
    | '/assinaturas'
    | '/contratos-falha'
    | '/chat/$contractId'
    | '/contratos/$contractId'
    | '/contratos/novo'
    | '/transacoes/$contractId'
    | '/transacoes/novo'
    | '/api/public/abacate-webhook'
    | '/api/public/health'
    | '/api/public/sitemap.xml'
    | '/chat'
    | '/contratos'
    | '/transacoes'
    | '/api/public/autentique-webhook/$'
    | '/api/public/sign/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/transactions'
    | '/_authenticated/_admin'
    | '/_authenticated/assinatura'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/nfs'
    | '/api/chat'
    | '/assinar/$token'
    | '/_authenticated/_admin/assinaturas'
    | '/_authenticated/_admin/contratos-falha'
    | '/_authenticated/chat/$contractId'
    | '/_authenticated/contratos/$contractId'
    | '/_authenticated/contratos/novo'
    | '/_authenticated/transacoes/$contractId'
    | '/_authenticated/transacoes/novo'
    | '/api/public/abacate-webhook'
    | '/api/public/health'
    | '/api/public/sitemap.xml'
    | '/_authenticated/chat/'
    | '/_authenticated/contratos/'
    | '/_authenticated/transacoes/'
    | '/api/public/autentique-webhook/$'
    | '/api/public/sign/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiChatRoute: typeof ApiChatRoute
  AssinarTokenRoute: typeof AssinarTokenRoute
  ApiPublicAbacateWebhookRoute: typeof ApiPublicAbacateWebhookRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicAutentiqueWebhookSplatRoute: typeof ApiPublicAutentiqueWebhookSplatRoute
  ApiPublicSignTokenRoute: typeof ApiPublicSignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar/$token': {
      id: '/assinar/$token'
      path: '/assinar/$token'
      fullPath: '/assinar/$token'
      preLoaderRoute: typeof AssinarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nfs': {
      id: '/_authenticated/nfs'
      path: '/nfs'
      fullPath: '/nfs'
      preLoaderRoute: typeof AuthenticatedNfsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transacoes/': {
      id: '/_authenticated/transacoes/'
      path: '/transacoes'
      fullPath: '/transacoes/'
      preLoaderRoute: typeof AuthenticatedTransacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/abacate-webhook': {
      id: '/api/public/abacate-webhook'
      path: '/api/public/abacate-webhook'
      fullPath: '/api/public/abacate-webhook'
      preLoaderRoute: typeof ApiPublicAbacateWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transacoes/novo': {
      id: '/_authenticated/transacoes/novo'
      path: '/transacoes/novo'
      fullPath: '/transacoes/novo'
      preLoaderRoute: typeof AuthenticatedTransacoesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transacoes/$contractId': {
      id: '/_authenticated/transacoes/$contractId'
      path: '/transacoes/$contractId'
      fullPath: '/transacoes/$contractId'
      preLoaderRoute: typeof AuthenticatedTransacoesContractIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/novo': {
      id: '/_authenticated/contratos/novo'
      path: '/contratos/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof AuthenticatedContratosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/$contractId': {
      id: '/_authenticated/contratos/$contractId'
      path: '/contratos/$contractId'
      fullPath: '/contratos/$contractId'
      preLoaderRoute: typeof AuthenticatedContratosContractIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$contractId': {
      id: '/_authenticated/chat/$contractId'
      path: '/chat/$contractId'
      fullPath: '/chat/$contractId'
      preLoaderRoute: typeof AuthenticatedChatContractIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/contratos-falha': {
      id: '/_authenticated/_admin/contratos-falha'
      path: '/contratos-falha'
      fullPath: '/contratos-falha'
      preLoaderRoute: typeof AuthenticatedAdminContratosFalhaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/assinaturas': {
      id: '/_authenticated/_admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAdminAssinaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/sign/$token': {
      id: '/api/public/sign/$token'
      path: '/api/public/sign/$token'
      fullPath: '/api/public/sign/$token'
      preLoaderRoute: typeof ApiPublicSignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autentique-webhook/$': {
      id: '/api/public/autentique-webhook/$'
      path: '/api/public/autentique-webhook/$'
      fullPath: '/api/public/autentique-webhook/$'
      preLoaderRoute: typeof ApiPublicAutentiqueWebhookSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAssinaturasRoute: typeof AuthenticatedAdminAssinaturasRoute
  AuthenticatedAdminContratosFalhaRoute: typeof AuthenticatedAdminContratosFalhaRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAssinaturasRoute: AuthenticatedAdminAssinaturasRoute,
    AuthenticatedAdminContratosFalhaRoute:
      AuthenticatedAdminContratosFalhaRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedNfsRoute: typeof AuthenticatedNfsRoute
  AuthenticatedChatContractIdRoute: typeof AuthenticatedChatContractIdRoute
  AuthenticatedContratosContractIdRoute: typeof AuthenticatedContratosContractIdRoute
  AuthenticatedContratosNovoRoute: typeof AuthenticatedContratosNovoRoute
  AuthenticatedTransacoesContractIdRoute: typeof AuthenticatedTransacoesContractIdRoute
  AuthenticatedTransacoesNovoRoute: typeof AuthenticatedTransacoesNovoRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
  AuthenticatedTransacoesIndexRoute: typeof AuthenticatedTransacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedNfsRoute: AuthenticatedNfsRoute,
  AuthenticatedChatContractIdRoute: AuthenticatedChatContractIdRoute,
  AuthenticatedContratosContractIdRoute: AuthenticatedContratosContractIdRoute,
  AuthenticatedContratosNovoRoute: AuthenticatedContratosNovoRoute,
  AuthenticatedTransacoesContractIdRoute:
    AuthenticatedTransacoesContractIdRoute,
  AuthenticatedTransacoesNovoRoute: AuthenticatedTransacoesNovoRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  AuthenticatedTransacoesIndexRoute: AuthenticatedTransacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  TransactionsRoute: TransactionsRoute,
  ApiChatRoute: ApiChatRoute,
  AssinarTokenRoute: AssinarTokenRoute,
  ApiPublicAbacateWebhookRoute: ApiPublicAbacateWebhookRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicAutentiqueWebhookSplatRoute: ApiPublicAutentiqueWebhookSplatRoute,
  ApiPublicSignTokenRoute: ApiPublicSignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
